server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:  #list
        - id: payment_routh
          uri: lb://cloud-payment-service # lb表示loadBalance
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言 路径相匹配的进行路由
        - id: payment_routh
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/port/**
            - Cookie=username,ddxx #判断cookie中必须含有“ username=ddxx”
            - After=2020-03-27T11:23:27.522+08:00[Asia/Shanghai] #判断是否在这个时间之后
            - Before=2020-04-27T11:23:27.522+08:00[Asia/Shanghai] #判断是否在这个时间之前
            - Between=2020-03-27T11:23:27.522+08:00[Asia/Shanghai],2020-04-27T11:23:27.522+08:00[Asia/Shanghai] #是否在两个时间中间
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，通过微服务名称进行路由
          enabled: true
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
