spring:
  application:
    name: cloud-payment-hystrix-service
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
