spring:
  application:
    name: cloud-order-feign-hystrix-service
  main:
    allow-bean-definition-overriding: true
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
    #不注册进eureka
    register-with-eureka: false
ribbon:
  #指的是建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间。
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
feign:
  hystrix:
    enabled: true
#logging:
#  level:
#    com.dx.cloud.service.PaymentService: debug